displayName=Sound Triggers
author=Tyler Lanphear
description=Play custom sounds when configurable in-game events occur
tags=sound,audio,triggers,hitsplat,notifications
version=1.0.2
plugins=com.soundtriggers.SoundTriggersPlugin
build=standard
